import { IndustryCategory } from '@/types/business';

/**
 * Default industry categories with associated search keywords
 * Each entry includes search terms you can use in Google, LinkedIn, Yelp, Clutch, or other directories
 * to find businesses that may need IT support.
 */
export const DEFAULT_INDUSTRIES: IndustryCategory[] = [
  {
    id: 'legal-services',
    name: 'Law Firms & Legal Services',
    keywords: [
      'law firm near me',
      'attorney office',
      'legal services',
      'lawyer near me',
      'corporate law firm',
      'family law attorney',
      'divorce lawyer',
      'criminal defense attorney',
      'business lawyer',
      'intellectual property attorney',
      'real estate lawyer',
      'personal injury attorney',
      'estate planning lawyer',
      'civil litigation attorney',
      'immigration lawyer',
      'bankruptcy attorney'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.justia.*',
      '*.findlaw.*',
      '*.avvo.*',
      '*.nolo.*',
      '*.superlawyers.*'
    ]
  },
  {
    id: 'accounting',
    name: 'Accounting & Tax Services',
    keywords: [
      'CPA firm near me',
      'accounting services',
      'tax preparation services',
      'bookkeeping services',
      'certified public accountant',
      'small business accountant',
      'tax advisor',
      'payroll services',
      'financial consulting',
      'business accounting firm',
      'tax return preparation',
      'QuickBooks accounting services',
      'audit services',
      'financial auditing firm'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.hrblock.*',
      '*.intuit.*',
      '*.turbotax.*',
      '*.libertytax.*'
    ]
  },
  {
    id: 'architecture',
    name: 'Architectural Services',
    keywords: [
      'architect near me',
      'architectural firm',
      'building design services',
      'residential architect',
      'commercial architecture firm',
      'architectural design services',
      'licensed architect',
      'sustainable design architect',
      'interior architecture',
      'landscape architect',
      'custom home architect',
      'building renovation architect',
      'urban design studio'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.archdaily.*',
      '*.houzz.*'
    ]
  },
  {
    id: 'medical-clinics',
    name: 'Medical Clinics',
    keywords: [
      'medical clinic near me',
      'primary care doctor',
      'family medical practice',
      'urgent care center',
      'walk-in clinic',
      'internal medicine clinic',
      'pediatric clinic',
      'family doctor',
      'healthcare provider',
      'medical center',
      'women\'s health clinic',
      'telehealth services',
      'medical practice'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.zocdoc.*',
      '*.healthgrades.*',
      '*.webmd.*',
      '*.doctolib.*'
    ]
  },
  {
    id: 'dental',
    name: 'Dental Offices',
    keywords: [
      'dentist near me',
      'dental office',
      'family dentist',
      'dental clinic',
      'cosmetic dentistry',
      'orthodontist near me',
      'dental implants',
      'emergency dental care',
      'pediatric dentist',
      'teeth whitening',
      'oral surgeon',
      'dental practice',
      'general dentistry'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.1-800-dentist.*',
      '*.zocdoc.*',
      '*.healthgrades.*'
    ]
  },
  {
    id: 'real-estate',
    name: 'Real Estate Agencies',
    keywords: [
      'real estate brokerage',
      'commercial real estate agency',
      'realtors near me',
      'residential real estate office',
      'real estate investment firm',
      'property sales agency',
      'property management company',
      'luxury real estate agent'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.zillow.*',
      '*.realtor.*',
      '*.redfin.*',
      '*.trulia.*',
      '*.homes.*'
    ]
  },
  {
    id: 'insurance',
    name: 'Insurance Agencies',
    keywords: [
      'insurance broker',
      'independent insurance agency',
      'commercial insurance providers',
      'homeowners insurance agency',
      'auto insurance agents',
      'life insurance advisors',
      'business insurance consultant'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.statefarm.*',
      '*.progressive.*',
      '*.geico.*',
      '*.farmers.*',
      '*.nationwide.*',
      '*.travelers.*',
      '*.allstate.*',
      '*.esurance.*'
    ]
  },
  {
    id: 'financial-advisory',
    name: 'Financial Advisory Services',
    keywords: [
      'wealth management firm',
      'financial planner near me',
      'investment advisory services',
      'fiduciary financial advisor',
      'retirement planning consultant',
      'fee-only financial planner',
      'private wealth management',
      'financial consulting firm'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.fidelity.*',
      '*.vanguard.*',
      '*.charlesschwab.*',
      '*.merrilledge.*'
    ]
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit Organizations',
    keywords: [
      '501c3 organizations',
      'nonprofit services',
      'charity organizations near me',
      'foundation services',
      'youth nonprofit programs',
      'education-based nonprofits',
      'grant-funded organization'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.guidestar.*',
      '*.charitynavigator.*'
    ]
  },
  {
    id: 'staffing',
    name: 'Staffing & Recruiting Firms',
    keywords: [
      'recruiting services',
      'staffing agency',
      'executive search firm',
      'temp agency',
      'IT staffing firm',
      'technical recruiter',
      'headhunting service',
      'staff augmentation company'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.indeed.*',
      '*.ziprecruiter.*',
      '*.monster.*',
      '*.glassdoor.*',
      '*.linkedin.*'
    ]
  },
  {
    id: 'event-services',
    name: 'Event Planning & Management',
    keywords: [
      'event planning services',
      'corporate event organizer',
      'wedding planner business',
      'party planner',
      'conference planning company',
      'event production services',
      'nonprofit event organizer'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.theknot.*',
      '*.weddingwire.*',
      '*.eventbrite.*'
    ]
  },
  {
    id: 'hospitality',
    name: 'Hospitality & Hotel Management',
    keywords: [
      'hotel management company',
      'hospitality services',
      'resort operations firms',
      'lodging management',
      'boutique hotel group',
      'hospitality consulting firms',
      'meeting and convention services'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.tripadvisor.*',
      '*.booking.*',
      '*.expedia.*',
      '*.hotels.*',
      '*.airbnb.*'
    ]
  },
  {
    id: 'engineering',
    name: 'Engineering Firms',
    keywords: [
      'mechanical engineering firm',
      'civil engineering services',
      'structural engineers near me',
      'electrical engineering consultants',
      'environmental engineering firm',
      'geotechnical services',
      'engineering project consultants'
    ],
    isCustom: false,
    domainBlacklist: []
  },
  {
    id: 'education',
    name: 'Private & Charter Schools',
    keywords: [
      'private school',
      'charter school',
      'independent school',
      'Montessori school',
      'Catholic school',
      'Christian school',
      'preparatory academy',
      'private academy'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.greatschools.*',
      '*.niche.*',
      '*.prepscholar.*',
      '*.schooldigger.*',
      '*.publicschoolreview.*',
      '*.usnews.*',
      '*.ed.gov',
      '*.state.*.us',
      '*.gov',
      '*.edu',
      '*.nces.ed.gov',
      '*.doe.*',
      '*.dph.*',
      '*.yelp.*',
      '*.yellowpages.*',
      '*.superpages.*',
      '*.whitepages.*'
    ]
  },
  {
    id: 'marketing-agency',
    name: 'Marketing & Creative Agencies',
    keywords: [
      'digital marketing agency',
      'marketing agency near me',
      'SEO company',
      'social media marketing',
      'advertising agency',
      'branding agency',
      'creative agency',
      'content marketing agency',
      'PPC advertising agency',
      'email marketing services',
      'web design agency',
      'graphic design services',
      'marketing consultants'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.fiverr.*',
      '*.upwork.*',
      '*.peopleperhour.*',
      '*.freelancer.*'
    ]
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Businesses',
    keywords: [
      'e-commerce business',
      'online store',
      'online retail',
      'digital marketplace',
      'direct to consumer brand',
      'dropshipping business',
      'e-commerce website',
      'internet retail',
      'online boutique',
      'online clothing store',
      'online merchant',
      'online retail store',
      'online sales',
      'online shop',
      'web store',
      'DTC brand',
      'ecommerce platform',
      'online business',
      'digital commerce',
      'retail website',
      'shopping website',
      'online marketplace',
      'subscription box service',
      'print on demand',
      'digital products store'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.amazon.*',
      '*.etsy.*',
      '*.ebay.*',
      '*.shopify.*',
      '*.woocommerce.*',
      '*.bigcommerce.*',
      '*.squarespace.*',
      '*.wix.*'
    ]
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing Companies',
    keywords: [
      'precision manufacturing',
      'industrial fabrication services',
      'OEM manufacturers',
      'custom machining',
      'contract manufacturing',
      'automated production',
      'industrial equipment manufacturers'
    ],
    isCustom: false,
    domainBlacklist: []
  },
  {
    id: 'logistics',
    name: 'Logistics & Supply Chain',
    keywords: [
      'freight logistics provider',
      'supply chain company',
      '3PL services near me',
      'transportation logistics',
      'warehouse fulfillment service',
      'distribution center services',
      'freight forwarding firm'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.ups.*',
      '*.fedex.*',
      '*.dhl.*'
    ]
  },
  {
    id: 'legal-saas',
    name: 'Legal Tech SaaS',
    keywords: [
      'legal software startup',
      'legal SaaS company',
      'contract automation platform',
      'compliance software',
      'case management software',
      'law practice management tools',
      'legal workflow automation',
      'legal technology company',
      'legaltech startup',
      'document automation software',
      'legal AI platform',
      'contract management software',
      'legal analytics platform',
      'e-discovery software',
      'legal research platform',
      'court filing software',
      'legal billing software',
      'client intake software',
      'legal CRM software',
      'litigation support software',
      'intellectual property software',
      'regulatory compliance platform',
      'legal document management',
      'virtual law firm platform',
      'legal practice automation'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.clio.*',
      '*.mycase.*',
      '*.practicepanther.*',
      '*.lawpay.*',
      '*.westlaw.*',
      '*.lexisnexis.*',
      '*.thomson.*',
      '*.relativity.*',
      '*.kira.*',
      '*.contract.*'
    ]
  },
  {
    id: 'pets',
    name: 'Pet Services',
    keywords: [
      'pet grooming near me',
      'dog groomer',
      'veterinary clinic',
      'animal hospital',
      'pet boarding near me',
      'dog daycare',
      'pet sitting services',
      'dog walker near me',
      'pet training services',
      'mobile pet grooming',
      'cat grooming',
      'pet spa',
      'dog training classes',
      'pet supplies store',
      'veterinarian near me'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.petco.*',
      '*.petsmart.*',
      '*.chewy.*'
    ]
  },
  {
    id: 'home-lifestyle-services',
    name: 'Home & Lifestyle Services',
    keywords: [
      'house cleaning service near me',
      'maid service',
      'lawn care service',
      'landscaping company near me',
      'handyman near me',
      'home repair contractor',
      'plumber near me',
      'electrician near me',
      'HVAC repair service',
      'carpet cleaning service',
      'window cleaning service',
      'gutter cleaning service',
      'pool maintenance service',
      'pest control service',
      'home security installation',
      'interior decorator near me',
      'personal chef service',
      'dog walker',
      'babysitter near me',
      'elderly care service',
      'home improvement contractor',
      'pressure washing service'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.angi.*',
      '*.homeadvisor.*',
      '*.thumbtack.*',
      '*.taskrabbit.*',
      '*.care.*',
      '*.sittercity.*',
      '*.rover.*',
      '*.wag.*',
      '*.handy.*',
      '*.porch.*',
      '*.houzz.*',
      '*.yelp.*',
      '*.google.*',
      '*.facebook.*'
    ]
  },
  {
    id: 'personal-health-wellness',
    name: 'Personal Health & Wellness',
    keywords: [
      'personal trainer near me',
      'yoga studio near me',
      'pilates classes near me',
      'massage therapist near me',
      'chiropractor near me',
      'acupuncture clinic',
      'physical therapy near me',
      'nutritionist near me',
      'weight loss clinic',
      'meditation center',
      'spa near me',
      'hair salon near me',
      'nail salon near me',
      'beauty salon',
      'barber shop near me',
      'tattoo shop near me',
      'piercing studio',
      'wellness center',
      'fitness gym near me',
      'crossfit gym',
      'martial arts classes',
      'dance studio near me',
      'life coach',
      'counseling services',
      'fitness center'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.classpass.*',
      '*.mindbody.*',
      '*.groupon.*',
      '*.livingwell.*',
      '*.webmd.*',
      '*.healthline.*',
      '*.mayoclinic.*',
      '*.psychology.*',
      '*.betterhelp.*',
      '*.talkspace.*',
      '*.zocdoc.*',
      '*.healthgrades.*',
      '*.vitals.*',
      '*.ratemds.*',
      '*.yelp.*',
      '*.google.*'
    ]
  },
  {
    id: 'entertainment-recreation',
    name: 'Entertainment & Recreation',
    keywords: [
      'movie theater near me',
      'bowling alley near me',
      'arcade near me',
      'mini golf near me',
      'escape room near me',
      'laser tag near me',
      'paintball near me',
      'go kart racing',
      'trampoline park near me',
      'amusement park',
      'water park',
      'ice skating rink',
      'roller skating rink',
      'rock climbing gym',
      'karaoke bar near me',
      'comedy club near me',
      'live music venue',
      'concert hall',
      'art gallery near me',
      'museum near me',
      'zoo near me',
      'aquarium',
      'theme restaurant',
      'sports bar near me',
      'pool hall near me',
      'casino near me',
      'bingo hall',
      'entertainment center'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.fandango.*',
      '*.movietickets.*',
      '*.ticketmaster.*',
      '*.stubhub.*',
      '*.eventbrite.*',
      '*.groupon.*',
      '*.tripadvisor.*',
      '*.foursquare.*',
      '*.yelp.*',
      '*.google.*',
      '*.facebook.*',
      '*.timeout.*',
      '*.expedia.*',
      '*.booking.*',
      '*.opentable.*'
    ]
  },
  {
    id: 'cybersecurity-services',
    name: 'Cybersecurity & IT Security',
    keywords: [
      'cybersecurity company near me',
      'IT security services',
      'penetration testing services',
      'security audit firm',
      'managed security services',
      'cyber threat assessment',
      'network security consultant',
      'data protection services',
      'security compliance consulting',
      'incident response services',
      'vulnerability assessment',
      'security awareness training',
      'endpoint security solutions',
      'cloud security services',
      'identity management services',
      'security operations center',
      'cyber risk assessment',
      'information security consultant',
      'GDPR compliance services',
      'SOC 2 compliance consulting',
      'security architecture consulting',
      'digital forensics services',
      'ransomware protection services',
      'security monitoring services',
      'cyber insurance consulting'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.crowdstrike.*',
      '*.paloaltonetworks.*',
      '*.checkpoint.*',
      '*.fortinet.*',
      '*.cisco.*',
      '*.symantec.*',
      '*.mcafee.*',
      '*.trendmicro.*',
      '*.kaspersky.*',
      '*.sophos.*',
      '*.fireeye.*',
      '*.proofpoint.*',
      '*.okta.*',
      '*.ping.*',
      '*.rapid7.*',
      '*.qualys.*',
      '*.tenable.*',
      '*.splunk.*'
    ]
  },
  {
    id: 'renewable-energy',
    name: 'Renewable Energy & Sustainability',
    keywords: [
      'solar panel installation near me',
      'solar energy company',
      'renewable energy consultant',
      'wind energy services',
      'energy efficiency audit',
      'green building consultant',
      'sustainable energy solutions',
      'solar panel installer',
      'energy storage systems',
      'electric vehicle charging stations',
      'geothermal energy systems',
      'energy management consulting',
      'carbon footprint assessment',
      'sustainability consulting',
      'LEED certification consulting',
      'energy retrofit services',
      'smart grid solutions',
      'battery storage installation',
      'solar farm development',
      'wind turbine installation',
      'hydroelectric systems',
      'biomass energy solutions',
      'energy procurement consulting',
      'net zero consulting',
      'environmental impact assessment',
      'green technology consulting',
      'renewable energy financing',
      'energy policy consulting'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.tesla.*',
      '*.sunpower.*',
      '*.solarcity.*',
      '*.sunrun.*',
      '*.vivint.*',
      '*.lg.*',
      '*.panasonic.*',
      '*.ge.*',
      '*.siemens.*',
      '*.vestas.*',
      '*.enercon.*',
      '*.goldwind.*',
      '*.solarworld.*',
      '*.firstsolar.*',
      '*.canadian.*',
      '*.jinko.*',
      '*.trina.*',
      '*.hanwha.*'
    ]
  },
  {
    id: 'digital-marketing-agencies',
    name: 'Digital Marketing & Advertising Agencies',
    keywords: [
      'digital marketing agency near me',
      'SEO services company',
      'social media marketing agency',
      'PPC advertising agency',
      'content marketing services',
      'email marketing agency',
      'web design and marketing',
      'brand strategy consulting',
      'influencer marketing agency',
      'marketing automation services',
      'conversion rate optimization',
      'online advertising agency',
      'search engine marketing',
      'digital advertising company',
      'performance marketing agency',
      'growth marketing services',
      'marketing analytics consulting',
      'video marketing services',
      'affiliate marketing agency',
      'mobile marketing services',
      'local SEO services',
      'e-commerce marketing agency',
      'B2B marketing agency',
      'lead generation services',
      'marketing strategy consulting',
      'creative advertising agency',
      'programmatic advertising',
      'marketing technology consulting',
      'customer acquisition services',
      'retention marketing services'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.google.*',
      '*.facebook.*',
      '*.meta.*',
      '*.linkedin.*',
      '*.twitter.*',
      '*.instagram.*',
      '*.youtube.*',
      '*.tiktok.*',
      '*.snapchat.*',
      '*.pinterest.*',
      '*.hubspot.*',
      '*.salesforce.*',
      '*.marketo.*',
      '*.mailchimp.*',
      '*.constantcontact.*',
      '*.hootsuite.*',
      '*.buffer.*',
      '*.sprout.*',
      '*.semrush.*',
      '*.ahrefs.*',
      '*.moz.*',
      '*.brightedge.*',
      '*.conductor.*'
    ]
  },
  {
    id: 'fintech-financial-services',
    name: 'FinTech & Financial Services',
    keywords: [
      'fintech startup',
      'financial technology company',
      'digital banking services',
      'payment processing company',
      'cryptocurrency exchange',
      'blockchain development services',
      'robo advisor platform',
      'peer to peer lending',
      'crowdfunding platform',
      'mobile payment solutions',
      'digital wallet services',
      'financial planning software',
      'investment management platform',
      'trading platform development',
      'regtech solutions',
      'insurtech company',
      'wealth management technology',
      'credit scoring platform',
      'fraud detection services',
      'compliance technology',
      'open banking solutions',
      'neobank services',
      'buy now pay later platform',
      'financial data analytics',
      'algorithmic trading platform',
      'digital lending platform',
      'expense management software',
      'accounting automation platform',
      'tax technology services',
      'financial API services'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.paypal.*',
      '*.stripe.*',
      '*.square.*',
      '*.visa.*',
      '*.mastercard.*',
      '*.amex.*',
      '*.discover.*',
      '*.coinbase.*',
      '*.binance.*',
      '*.kraken.*',
      '*.robinhood.*',
      '*.schwab.*',
      '*.fidelity.*',
      '*.vanguard.*',
      '*.etrade.*',
      '*.tdameritrade.*',
      '*.mint.*',
      '*.quickbooks.*',
      '*.xero.*',
      '*.freshbooks.*',
      '*.wave.*',
      '*.plaid.*',
      '*.yodlee.*',
      '*.intuit.*'
    ]
  },
  {
    id: 'healthcare-technology',
    name: 'Healthcare Technology & MedTech',
    keywords: [
      'healthcare technology company',
      'medical device manufacturer',
      'telemedicine platform',
      'health information systems',
      'electronic health records',
      'medical software development',
      'healthcare analytics platform',
      'digital health solutions',
      'medical imaging technology',
      'patient management software',
      'clinical trial software',
      'medical billing software',
      'healthcare compliance software',
      'remote patient monitoring',
      'medical AI platform',
      'diagnostic software',
      'pharmacy management system',
      'hospital management software',
      'medical practice management',
      'healthcare CRM software',
      'medical device software',
      'clinical decision support',
      'population health management',
      'healthcare data analytics',
      'medical research platform',
      'biomedical technology',
      'health monitoring devices',
      'medical robotics company',
      'surgical technology',
      'rehabilitation technology',
      'mental health technology',
      'wellness platform',
      'fitness tracking technology'
    ],
    isCustom: false,
    domainBlacklist: [
      '*.epic.*',
      '*.cerner.*',
      '*.allscripts.*',
      '*.athenahealth.*',
      '*.eclinicalworks.*',
      '*.nextgen.*',
      '*.ge.*',
      '*.siemens.*',
      '*.philips.*',
      '*.medtronic.*',
      '*.abbott.*',
      '*.johnson.*',
      '*.pfizer.*',
      '*.roche.*',
      '*.novartis.*',
      '*.merck.*',
      '*.bayer.*',
      '*.sanofi.*',
      '*.gsk.*',
      '*.astrazeneca.*',
      '*.lilly.*',
      '*.amgen.*',
      '*.gilead.*',
      '*.biogen.*'
    ]
  },
];

/**
 * Contact page keywords for scraping
 */
export const CONTACT_KEYWORDS = [
  'contact',
  'about us',
  'corporate',
  'investor',
  'team',
  'staff',
  'directory',
  'location',
  'office',
];