import { IndustryCategory, IndustrySubCategory } from '@/types/business'

/**
 * Default sub-categories for organizing industries
 */
export const DEFAULT_SUB_CATEGORIES: IndustrySubCategory[] = [
  {
    id: 'it-services',
    name: 'IT Services',
    description: 'Technology companies and IT service providers',
    isExpanded: false,
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    description: 'Legal, accounting, consulting, and other professional services',
    isExpanded: true, // Default expanded as per requirements
  },
  {
    id: 'healthcare-medical',
    name: 'Healthcare & Medical',
    description: 'Medical practices, clinics, and healthcare technology',
    isExpanded: false,
  },
  {
    id: 'commercial-trade-construction',
    name: 'Commercial Trade & Construction (B2B)',
    description: 'Manufacturing, logistics, and commercial construction services',
    isExpanded: false,
  },
  {
    id: 'food-service-dining',
    name: 'Food Service & Dining (B2C)',
    description: 'Restaurants, cafes, and food service establishments',
    isExpanded: false,
  },
  {
    id: 'retail-consumer-services',
    name: 'Retail & Consumer Services (B2C)',
    description: 'Retail stores, personal services, and consumer-facing businesses',
    isExpanded: false,
  },
  {
    id: 'real-estate-property',
    name: 'Real Estate & Property',
    description: 'Real estate agencies and property technology services',
    isExpanded: false,
  },
  {
    id: 'financial-services',
    name: 'Financial Services',
    description: 'Insurance, financial advisory, and FinTech companies',
    isExpanded: false,
  },
]

/**
 * Default industry categories with associated search keywords and sub-category assignments
 * Each entry includes search terms you can use in Google, LinkedIn, Yelp, Clutch, or other directories
 * to find businesses that may need IT support.
 */
export const DEFAULT_INDUSTRIES: IndustryCategory[] = [
  {
    id: 'legal-services',
    name: 'Law Firms & Legal Services',
    keywords: [
      'law firm near me',
      'attorney office',
      'legal services',
      'lawyer near me',
      'corporate law firm',
      'family law attorney',
      'divorce lawyer',
      'criminal defense attorney',
      'business lawyer',
      'intellectual property attorney',
      'real estate lawyer',
      'personal injury attorney',
      'estate planning lawyer',
      'civil litigation attorney',
      'immigration lawyer',
      'bankruptcy attorney',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.justia.*', '*.findlaw.*', '*.avvo.*', '*.nolo.*', '*.superlawyers.*'],
  },
  {
    id: 'accounting',
    name: 'Accounting & Tax Services',
    keywords: [
      'CPA firm near me',
      'accounting services',
      'tax preparation services',
      'bookkeeping services',
      'certified public accountant',
      'small business accountant',
      'tax advisor',
      'payroll services',
      'financial consulting',
      'business accounting firm',
      'tax return preparation',
      'QuickBooks accounting services',
      'audit services',
      'financial auditing firm',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.hrblock.*', '*.intuit.*', '*.turbotax.*', '*.libertytax.*'],
  },
  {
    id: 'architecture',
    name: 'Architectural Services',
    keywords: [
      'architect near me',
      'architectural firm',
      'building design services',
      'residential architect',
      'commercial architecture firm',
      'architectural design services',
      'licensed architect',
      'sustainable design architect',
      'interior architecture',
      'landscape architect',
      'custom home architect',
      'building renovation architect',
      'urban design studio',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.archdaily.*', '*.houzz.*'],
  },
  {
    id: 'medical-clinics',
    name: 'Medical Clinics',
    keywords: [
      'medical clinic near me',
      'primary care doctor',
      'family medical practice',
      'urgent care center',
      'walk-in clinic',
      'internal medicine clinic',
      'pediatric clinic',
      'family doctor',
      'healthcare provider',
      'medical center',
      "women's health clinic",
      'telehealth services',
      'medical practice',
    ],
    isCustom: false,
    subCategoryId: 'healthcare-medical',
    domainBlacklist: ['*.zocdoc.*', '*.healthgrades.*', '*.webmd.*', '*.doctolib.*'],
  },
  {
    id: 'dental',
    name: 'Dental Offices',
    keywords: [
      'dentist near me',
      'dental office',
      'family dentist',
      'dental clinic',
      'cosmetic dentistry',
      'orthodontist near me',
      'dental implants',
      'emergency dental care',
      'pediatric dentist',
      'teeth whitening',
      'oral surgeon',
      'dental practice',
      'general dentistry',
    ],
    isCustom: false,
    subCategoryId: 'healthcare-medical',
    domainBlacklist: ['*.1-800-dentist.*', '*.zocdoc.*', '*.healthgrades.*'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate Agencies',
    keywords: [
      'real estate brokerage',
      'commercial real estate agency',
      'realtors near me',
      'residential real estate office',
      'real estate investment firm',
      'property sales agency',
      'property management company',
      'luxury real estate agent',
    ],
    isCustom: false,
    subCategoryId: 'real-estate-property',
    domainBlacklist: ['*.zillow.*', '*.realtor.*', '*.redfin.*', '*.trulia.*', '*.homes.*'],
  },
  {
    id: 'insurance',
    name: 'Insurance Agencies',
    keywords: [
      'insurance broker',
      'independent insurance agency',
      'commercial insurance providers',
      'homeowners insurance agency',
      'auto insurance agents',
      'life insurance advisors',
      'business insurance consultant',
    ],
    isCustom: false,
    subCategoryId: 'financial-services',
    domainBlacklist: [
      '*.statefarm.*',
      '*.progressive.*',
      '*.geico.*',
      '*.farmers.*',
      '*.nationwide.*',
      '*.travelers.*',
      '*.allstate.*',
      '*.esurance.*',
    ],
  },
  {
    id: 'financial-advisory',
    name: 'Financial Advisory Services',
    keywords: [
      'wealth management firm',
      'financial planner near me',
      'investment advisory services',
      'fiduciary financial advisor',
      'retirement planning consultant',
      'fee-only financial planner',
      'private wealth management',
      'financial consulting firm',
    ],
    isCustom: false,
    subCategoryId: 'financial-services',
    domainBlacklist: ['*.fidelity.*', '*.vanguard.*', '*.charlesschwab.*', '*.merrilledge.*'],
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit Organizations',
    keywords: [
      '501c3 organizations',
      'nonprofit services',
      'charity organizations near me',
      'foundation services',
      'youth nonprofit programs',
      'education-based nonprofits',
      'grant-funded organization',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.guidestar.*', '*.charitynavigator.*'],
  },
  {
    id: 'staffing',
    name: 'Staffing & Recruiting Firms',
    keywords: [
      'recruiting services',
      'staffing agency',
      'executive search firm',
      'temp agency',
      'IT staffing firm',
      'technical recruiter',
      'headhunting service',
      'staff augmentation company',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: [
      '*.indeed.*',
      '*.ziprecruiter.*',
      '*.monster.*',
      '*.glassdoor.*',
      '*.linkedin.*',
    ],
  },
  {
    id: 'event-services',
    name: 'Event Planning & Management',
    keywords: [
      'event planning services',
      'corporate event organizer',
      'wedding planner business',
      'party planner',
      'conference planning company',
      'event production services',
      'nonprofit event organizer',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.theknot.*', '*.weddingwire.*', '*.eventbrite.*'],
  },
  {
    id: 'hospitality',
    name: 'Hospitality & Hotel Management',
    keywords: [
      'hotel management company',
      'hospitality services',
      'resort operations firms',
      'lodging management',
      'boutique hotel group',
      'hospitality consulting firms',
      'meeting and convention services',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: ['*.tripadvisor.*', '*.booking.*', '*.expedia.*', '*.hotels.*', '*.airbnb.*'],
  },
  {
    id: 'engineering',
    name: 'Engineering Firms',
    keywords: [
      'mechanical engineering firm',
      'civil engineering services',
      'structural engineers near me',
      'electrical engineering consultants',
      'environmental engineering firm',
      'geotechnical services',
      'engineering project consultants',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: [],
  },
  {
    id: 'education',
    name: 'Private & Charter Schools',
    keywords: [
      'private school',
      'charter school',
      'independent school',
      'Montessori school',
      'Catholic school',
      'Christian school',
      'preparatory academy',
      'private academy',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: [
      '*.greatschools.*',
      '*.niche.*',
      '*.prepscholar.*',
      '*.schooldigger.*',
      '*.publicschoolreview.*',
      '*.usnews.*',
      '*.ed.gov',
      '*.state.*.us',
      '*.gov',
      '*.edu',
      '*.nces.ed.gov',
      '*.doe.*',
      '*.dph.*',
      '*.yelp.*',
      '*.yellowpages.*',
      '*.superpages.*',
      '*.whitepages.*',
    ],
  },
  {
    id: 'marketing-agency',
    name: 'Marketing & Creative Agencies',
    keywords: [
      'digital marketing agency',
      'marketing agency near me',
      'SEO company',
      'social media marketing',
      'advertising agency',
      'branding agency',
      'creative agency',
      'content marketing agency',
      'PPC advertising agency',
      'email marketing services',
      'web design agency',
      'graphic design services',
      'marketing consultants',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.fiverr.*', '*.upwork.*', '*.peopleperhour.*', '*.freelancer.*'],
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Businesses',
    keywords: [
      'e-commerce business',
      'online store',
      'online retail',
      'digital marketplace',
      'direct to consumer brand',
      'dropshipping business',
      'e-commerce website',
      'internet retail',
      'online boutique',
      'online clothing store',
      'online merchant',
      'online retail store',
      'online sales',
      'online shop',
      'web store',
      'DTC brand',
      'ecommerce platform',
      'online business',
      'digital commerce',
      'retail website',
      'shopping website',
      'online marketplace',
      'subscription box service',
      'print on demand',
      'digital products store',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.amazon.*',
      '*.etsy.*',
      '*.ebay.*',
      '*.shopify.*',
      '*.woocommerce.*',
      '*.bigcommerce.*',
      '*.squarespace.*',
      '*.wix.*',
    ],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing Companies',
    keywords: [
      'precision manufacturing',
      'industrial fabrication services',
      'OEM manufacturers',
      'custom machining',
      'contract manufacturing',
      'automated production',
      'industrial equipment manufacturers',
    ],
    isCustom: false,
    subCategoryId: 'commercial-trade-construction',
    domainBlacklist: [],
  },
  {
    id: 'logistics',
    name: 'Logistics & Supply Chain',
    keywords: [
      'freight logistics provider',
      'supply chain company',
      '3PL services near me',
      'transportation logistics',
      'warehouse fulfillment service',
      'distribution center services',
      'freight forwarding firm',
    ],
    isCustom: false,
    subCategoryId: 'commercial-trade-construction',
    domainBlacklist: ['*.ups.*', '*.fedex.*', '*.dhl.*'],
  },
  {
    id: 'legal-saas',
    name: 'Legal Tech SaaS',
    keywords: [
      'legal software startup',
      'legal SaaS company',
      'contract automation platform',
      'compliance software',
      'case management software',
      'law practice management tools',
      'legal workflow automation',
      'legal technology company',
      'legaltech startup',
      'document automation software',
      'legal AI platform',
      'contract management software',
      'legal analytics platform',
      'e-discovery software',
      'legal research platform',
      'court filing software',
      'legal billing software',
      'client intake software',
      'legal CRM software',
      'litigation support software',
      'intellectual property software',
      'regulatory compliance platform',
      'legal document management',
      'virtual law firm platform',
      'legal practice automation',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.clio.*',
      '*.mycase.*',
      '*.practicepanther.*',
      '*.lawpay.*',
      '*.westlaw.*',
      '*.lexisnexis.*',
      '*.thomson.*',
      '*.relativity.*',
      '*.kira.*',
      '*.contract.*',
    ],
  },
  {
    id: 'pets',
    name: 'Pet Services',
    keywords: [
      'pet grooming near me',
      'dog groomer',
      'veterinary clinic',
      'animal hospital',
      'pet boarding near me',
      'dog daycare',
      'pet sitting services',
      'dog walker near me',
      'pet training services',
      'mobile pet grooming',
      'cat grooming',
      'pet spa',
      'dog training classes',
      'pet supplies store',
      'veterinarian near me',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: ['*.petco.*', '*.petsmart.*', '*.chewy.*'],
  },
  {
    id: 'home-lifestyle-services',
    name: 'Home & Lifestyle Services',
    keywords: [
      'house cleaning service near me',
      'maid service',
      'lawn care service',
      'landscaping company near me',
      'handyman near me',
      'home repair contractor',
      'plumber near me',
      'electrician near me',
      'HVAC repair service',
      'carpet cleaning service',
      'window cleaning service',
      'gutter cleaning service',
      'pool maintenance service',
      'pest control service',
      'home security installation',
      'interior decorator near me',
      'personal chef service',
      'dog walker',
      'babysitter near me',
      'elderly care service',
      'home improvement contractor',
      'pressure washing service',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.angi.*',
      '*.homeadvisor.*',
      '*.thumbtack.*',
      '*.taskrabbit.*',
      '*.care.*',
      '*.sittercity.*',
      '*.rover.*',
      '*.wag.*',
      '*.handy.*',
      '*.porch.*',
      '*.houzz.*',
      '*.yelp.*',
      '*.google.*',
      '*.facebook.*',
    ],
  },
  {
    id: 'personal-health-wellness',
    name: 'Personal Health & Wellness',
    keywords: [
      'personal trainer near me',
      'yoga studio near me',
      'pilates classes near me',
      'massage therapist near me',
      'chiropractor near me',
      'acupuncture clinic',
      'physical therapy near me',
      'nutritionist near me',
      'weight loss clinic',
      'meditation center',
      'spa near me',
      'hair salon near me',
      'nail salon near me',
      'beauty salon',
      'barber shop near me',
      'tattoo shop near me',
      'piercing studio',
      'wellness center',
      'fitness gym near me',
      'crossfit gym',
      'martial arts classes',
      'dance studio near me',
      'life coach',
      'counseling services',
      'fitness center',
    ],
    isCustom: false,
    subCategoryId: 'healthcare-medical',
    domainBlacklist: [
      '*.classpass.*',
      '*.mindbody.*',
      '*.groupon.*',
      '*.livingwell.*',
      '*.webmd.*',
      '*.healthline.*',
      '*.mayoclinic.*',
      '*.psychology.*',
      '*.betterhelp.*',
      '*.talkspace.*',
      '*.zocdoc.*',
      '*.healthgrades.*',
      '*.vitals.*',
      '*.ratemds.*',
      '*.yelp.*',
      '*.google.*',
    ],
  },
  {
    id: 'entertainment-recreation',
    name: 'Entertainment & Recreation',
    keywords: [
      'movie theater near me',
      'bowling alley near me',
      'arcade near me',
      'mini golf near me',
      'escape room near me',
      'laser tag near me',
      'paintball near me',
      'go kart racing',
      'trampoline park near me',
      'amusement park',
      'water park',
      'ice skating rink',
      'roller skating rink',
      'rock climbing gym',
      'karaoke bar near me',
      'comedy club near me',
      'live music venue',
      'concert hall',
      'art gallery near me',
      'museum near me',
      'zoo near me',
      'aquarium',
      'theme restaurant',
      'sports bar near me',
      'pool hall near me',
      'casino near me',
      'bingo hall',
      'entertainment center',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.fandango.*',
      '*.movietickets.*',
      '*.ticketmaster.*',
      '*.stubhub.*',
      '*.eventbrite.*',
      '*.groupon.*',
      '*.tripadvisor.*',
      '*.foursquare.*',
      '*.yelp.*',
      '*.google.*',
      '*.facebook.*',
      '*.timeout.*',
      '*.expedia.*',
      '*.booking.*',
      '*.opentable.*',
    ],
  },
  {
    id: 'cybersecurity-services',
    name: 'Cybersecurity & IT Security',
    keywords: [
      'cybersecurity company near me',
      'IT security services',
      'penetration testing services',
      'security audit firm',
      'managed security services',
      'cyber threat assessment',
      'network security consultant',
      'data protection services',
      'security compliance consulting',
      'incident response services',
      'vulnerability assessment',
      'security awareness training',
      'endpoint security solutions',
      'cloud security services',
      'identity management services',
      'security operations center',
      'cyber risk assessment',
      'information security consultant',
      'GDPR compliance services',
      'SOC 2 compliance consulting',
      'security architecture consulting',
      'digital forensics services',
      'ransomware protection services',
      'security monitoring services',
      'cyber insurance consulting',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.crowdstrike.*',
      '*.paloaltonetworks.*',
      '*.checkpoint.*',
      '*.fortinet.*',
      '*.cisco.*',
      '*.symantec.*',
      '*.mcafee.*',
      '*.trendmicro.*',
      '*.kaspersky.*',
      '*.sophos.*',
      '*.fireeye.*',
      '*.proofpoint.*',
      '*.okta.*',
      '*.ping.*',
      '*.rapid7.*',
      '*.qualys.*',
      '*.tenable.*',
      '*.splunk.*',
    ],
  },
  {
    id: 'renewable-energy',
    name: 'Renewable Energy & Sustainability',
    keywords: [
      'solar panel installation near me',
      'solar energy company',
      'renewable energy consultant',
      'wind energy services',
      'energy efficiency audit',
      'green building consultant',
      'sustainable energy solutions',
      'solar panel installer',
      'energy storage systems',
      'electric vehicle charging stations',
      'geothermal energy systems',
      'energy management consulting',
      'carbon footprint assessment',
      'sustainability consulting',
      'LEED certification consulting',
      'energy retrofit services',
      'smart grid solutions',
      'battery storage installation',
      'solar farm development',
      'wind turbine installation',
      'hydroelectric systems',
      'biomass energy solutions',
      'energy procurement consulting',
      'net zero consulting',
      'environmental impact assessment',
      'green technology consulting',
      'renewable energy financing',
      'energy policy consulting',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.tesla.*',
      '*.sunpower.*',
      '*.solarcity.*',
      '*.sunrun.*',
      '*.vivint.*',
      '*.lg.*',
      '*.panasonic.*',
      '*.ge.*',
      '*.siemens.*',
      '*.vestas.*',
      '*.enercon.*',
      '*.goldwind.*',
      '*.solarworld.*',
      '*.firstsolar.*',
      '*.canadian.*',
      '*.jinko.*',
      '*.trina.*',
      '*.hanwha.*',
    ],
  },
  {
    id: 'digital-marketing-agencies',
    name: 'Digital Marketing & Advertising Agencies',
    keywords: [
      'digital marketing agency near me',
      'SEO services company',
      'social media marketing agency',
      'PPC advertising agency',
      'content marketing services',
      'email marketing agency',
      'web design and marketing',
      'brand strategy consulting',
      'influencer marketing agency',
      'marketing automation services',
      'conversion rate optimization',
      'online advertising agency',
      'search engine marketing',
      'digital advertising company',
      'performance marketing agency',
      'growth marketing services',
      'marketing analytics consulting',
      'video marketing services',
      'affiliate marketing agency',
      'mobile marketing services',
      'local SEO services',
      'e-commerce marketing agency',
      'B2B marketing agency',
      'lead generation services',
      'marketing strategy consulting',
      'creative advertising agency',
      'programmatic advertising',
      'marketing technology consulting',
      'customer acquisition services',
      'retention marketing services',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: [
      '*.google.*',
      '*.facebook.*',
      '*.meta.*',
      '*.linkedin.*',
      '*.twitter.*',
      '*.instagram.*',
      '*.youtube.*',
      '*.tiktok.*',
      '*.snapchat.*',
      '*.pinterest.*',
      '*.hubspot.*',
      '*.salesforce.*',
      '*.marketo.*',
      '*.mailchimp.*',
      '*.constantcontact.*',
      '*.hootsuite.*',
      '*.buffer.*',
      '*.sprout.*',
      '*.semrush.*',
      '*.ahrefs.*',
      '*.moz.*',
      '*.brightedge.*',
      '*.conductor.*',
    ],
  },
  {
    id: 'fintech-financial-services',
    name: 'FinTech & Financial Services',
    keywords: [
      'fintech startup',
      'financial technology company',
      'digital banking services',
      'payment processing company',
      'cryptocurrency exchange',
      'blockchain development services',
      'robo advisor platform',
      'peer to peer lending',
      'crowdfunding platform',
      'mobile payment solutions',
      'digital wallet services',
      'financial planning software',
      'investment management platform',
      'trading platform development',
      'regtech solutions',
      'insurtech company',
      'wealth management technology',
      'credit scoring platform',
      'fraud detection services',
      'compliance technology',
      'open banking solutions',
      'neobank services',
      'buy now pay later platform',
      'financial data analytics',
      'algorithmic trading platform',
      'digital lending platform',
      'expense management software',
      'accounting automation platform',
      'tax technology services',
      'financial API services',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.paypal.*',
      '*.stripe.*',
      '*.square.*',
      '*.visa.*',
      '*.mastercard.*',
      '*.amex.*',
      '*.discover.*',
      '*.coinbase.*',
      '*.binance.*',
      '*.kraken.*',
      '*.robinhood.*',
      '*.schwab.*',
      '*.fidelity.*',
      '*.vanguard.*',
      '*.etrade.*',
      '*.tdameritrade.*',
      '*.mint.*',
      '*.quickbooks.*',
      '*.xero.*',
      '*.freshbooks.*',
      '*.wave.*',
      '*.plaid.*',
      '*.yodlee.*',
      '*.intuit.*',
    ],
  },
  {
    id: 'healthcare-technology',
    name: 'Healthcare Technology & MedTech',
    keywords: [
      'healthcare technology company',
      'medical device manufacturer',
      'telemedicine platform',
      'health information systems',
      'electronic health records',
      'medical software development',
      'healthcare analytics platform',
      'digital health solutions',
      'medical imaging technology',
      'patient management software',
      'clinical trial software',
      'medical billing software',
      'healthcare compliance software',
      'remote patient monitoring',
      'medical AI platform',
      'diagnostic software',
      'pharmacy management system',
      'hospital management software',
      'medical practice management',
      'healthcare CRM software',
      'medical device software',
      'clinical decision support',
      'population health management',
      'healthcare data analytics',
      'medical research platform',
      'biomedical technology',
      'health monitoring devices',
      'medical robotics company',
      'surgical technology',
      'rehabilitation technology',
      'mental health technology',
      'wellness platform',
      'fitness tracking technology',
    ],
    isCustom: false,
    subCategoryId: 'healthcare-medical',
    domainBlacklist: [
      '*.epic.*',
      '*.cerner.*',
      '*.allscripts.*',
      '*.athenahealth.*',
      '*.eclinicalworks.*',
      '*.nextgen.*',
      '*.ge.*',
      '*.siemens.*',
      '*.philips.*',
      '*.medtronic.*',
      '*.abbott.*',
      '*.johnson.*',
      '*.pfizer.*',
      '*.roche.*',
      '*.novartis.*',
      '*.merck.*',
      '*.bayer.*',
      '*.sanofi.*',
      '*.gsk.*',
      '*.astrazeneca.*',
      '*.lilly.*',
      '*.amgen.*',
      '*.gilead.*',
      '*.biogen.*',
    ],
  },
  {
    id: 'artificial-intelligence-ml',
    name: 'AI & Machine Learning',
    keywords: [
      'AI consulting company',
      'machine learning services',
      'artificial intelligence development',
      'ML model development',
      'computer vision solutions',
      'natural language processing',
      'AI automation services',
      'deep learning consulting',
      'neural network development',
      'AI software development',
      'predictive analytics services',
      'AI chatbot development',
      'robotic process automation',
      'AI data analysis',
      'machine learning consulting',
      'AI implementation services',
      'intelligent automation',
      'AI strategy consulting',
      'custom AI solutions',
      'AI training services',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.openai.*',
      '*.anthropic.*',
      '*.google.*',
      '*.microsoft.*',
      '*.amazon.*',
      '*.ibm.*',
      '*.nvidia.*',
      '*.tensorflow.*',
      '*.pytorch.*',
      '*.huggingface.*',
      '*.databricks.*',
      '*.palantir.*',
      '*.snowflake.*',
      '*.dataiku.*',
      '*.h2o.*',
      '*.alteryx.*',
      '*.sas.*',
      '*.tableau.*',
    ],
  },
  {
    id: 'ecommerce-retail-tech',
    name: 'E-commerce & Retail Technology',
    keywords: [
      'e-commerce development',
      'online store development',
      'retail technology solutions',
      'e-commerce platform development',
      'shopping cart development',
      'payment gateway integration',
      'inventory management software',
      'POS system development',
      'retail analytics platform',
      'e-commerce consulting',
      'omnichannel retail solutions',
      'marketplace development',
      'dropshipping platform',
      'subscription commerce platform',
      'mobile commerce development',
      'retail automation software',
      'customer loyalty platform',
      'product recommendation engine',
      'retail CRM software',
      'e-commerce SEO services',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.shopify.*',
      '*.woocommerce.*',
      '*.magento.*',
      '*.bigcommerce.*',
      '*.squarespace.*',
      '*.wix.*',
      '*.amazon.*',
      '*.ebay.*',
      '*.etsy.*',
      '*.walmart.*',
      '*.target.*',
      '*.bestbuy.*',
      '*.stripe.*',
      '*.paypal.*',
      '*.square.*',
      '*.lightspeed.*',
      '*.toast.*',
      '*.clover.*',
    ],
  },
  {
    id: 'blockchain-cryptocurrency',
    name: 'Blockchain & Cryptocurrency',
    keywords: [
      'blockchain development',
      'cryptocurrency exchange development',
      'smart contract development',
      'DeFi platform development',
      'NFT marketplace development',
      'blockchain consulting',
      'crypto wallet development',
      'blockchain security audit',
      'tokenization services',
      'cryptocurrency mining',
      'blockchain integration',
      'Web3 development',
      'decentralized application development',
      'crypto trading platform',
      'blockchain analytics',
      'cryptocurrency compliance',
      'digital asset management',
      'blockchain infrastructure',
      'crypto payment processing',
      'blockchain as a service',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.coinbase.*',
      '*.binance.*',
      '*.kraken.*',
      '*.gemini.*',
      '*.bitfinex.*',
      '*.huobi.*',
      '*.okx.*',
      '*.kucoin.*',
      '*.crypto.*',
      '*.blockchain.*',
      '*.ethereum.*',
      '*.bitcoin.*',
      '*.consensys.*',
      '*.chainlink.*',
      '*.polygon.*',
      '*.solana.*',
      '*.avalanche.*',
      '*.cardano.*',
    ],
  },
  {
    id: 'iot-smart-devices',
    name: 'IoT & Smart Devices',
    keywords: [
      'IoT development services',
      'smart device development',
      'Internet of Things consulting',
      'connected device development',
      'IoT platform development',
      'smart home automation',
      'industrial IoT solutions',
      'IoT sensor development',
      'smart city technology',
      'wearable device development',
      'IoT data analytics',
      'edge computing solutions',
      'IoT security services',
      'smart building technology',
      'IoT cloud platform',
      'device connectivity solutions',
      'IoT firmware development',
      'smart agriculture technology',
      'IoT monitoring systems',
      'wireless sensor networks',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.amazon.*',
      '*.google.*',
      '*.microsoft.*',
      '*.apple.*',
      '*.samsung.*',
      '*.cisco.*',
      '*.intel.*',
      '*.qualcomm.*',
      '*.arm.*',
      '*.bosch.*',
      '*.siemens.*',
      '*.ge.*',
      '*.honeywell.*',
      '*.schneider.*',
      '*.abb.*',
      '*.rockwell.*',
      '*.emerson.*',
      '*.philips.*',
    ],
  },
  {
    id: 'edtech-elearning',
    name: 'EdTech & E-Learning',
    keywords: [
      'e-learning platform development',
      'educational technology',
      'online course platform',
      'learning management system',
      'educational app development',
      'virtual classroom software',
      'student information system',
      'educational content creation',
      'adaptive learning platform',
      'microlearning solutions',
      'gamification in education',
      'educational analytics',
      'online tutoring platform',
      'skill assessment platform',
      'corporate training software',
      'educational VR/AR solutions',
      'language learning app',
      'STEM education technology',
      'educational AI platform',
      'remote learning solutions',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.coursera.*',
      '*.udemy.*',
      '*.edx.*',
      '*.khan.*',
      '*.pluralsight.*',
      '*.linkedin.*',
      '*.skillshare.*',
      '*.masterclass.*',
      '*.blackboard.*',
      '*.canvas.*',
      '*.moodle.*',
      '*.schoology.*',
      '*.google.*',
      '*.microsoft.*',
      '*.zoom.*',
      '*.pearson.*',
      '*.mcgraw.*',
      '*.cengage.*',
    ],
  },
  {
    id: 'proptech-real-estate',
    name: 'PropTech & Real Estate Technology',
    keywords: [
      'real estate technology',
      'property management software',
      'real estate CRM',
      'property listing platform',
      'real estate analytics',
      'virtual property tours',
      'property valuation software',
      'real estate investment platform',
      'tenant screening software',
      'lease management system',
      'real estate marketing automation',
      'property maintenance software',
      'real estate transaction platform',
      'mortgage technology',
      'real estate data analytics',
      'property search platform',
      'real estate mobile app',
      'smart building management',
      'real estate blockchain',
      'property crowdfunding platform',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.zillow.*',
      '*.realtor.*',
      '*.redfin.*',
      '*.trulia.*',
      '*.apartments.*',
      '*.rent.*',
      '*.loopnet.*',
      '*.costar.*',
      '*.mls.*',
      '*.yardi.*',
      '*.appfolio.*',
      '*.buildium.*',
      '*.rentmanager.*',
      '*.propertyware.*',
      '*.realpage.*',
      '*.entrata.*',
      '*.resman.*',
      '*.onesite.*',
    ],
  },
  {
    id: 'agtech-agriculture',
    name: 'AgTech & Agriculture Technology',
    keywords: [
      'precision agriculture technology',
      'farm management software',
      'agricultural drone services',
      'crop monitoring systems',
      'smart farming solutions',
      'agricultural IoT sensors',
      'livestock monitoring technology',
      'soil analysis technology',
      'irrigation management systems',
      'agricultural data analytics',
      'farm automation systems',
      'agricultural robotics',
      'crop yield optimization',
      'agricultural weather monitoring',
      'farm equipment tracking',
      'agricultural supply chain',
      'greenhouse automation',
      'agricultural AI solutions',
      'sustainable farming technology',
      'agricultural marketplace platform',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.johndeere.*',
      '*.monsanto.*',
      '*.bayer.*',
      '*.syngenta.*',
      '*.dupont.*',
      '*.corteva.*',
      '*.cargill.*',
      '*.adm.*',
      '*.tyson.*',
      '*.trimble.*',
      '*.climate.*',
      '*.farmers.*',
      '*.pioneer.*',
      '*.agco.*',
      '*.cnhi.*',
      '*.kubota.*',
      '*.claas.*',
      '*.fendt.*',
    ],
  },
  {
    id: 'gaming-entertainment-tech',
    name: 'Gaming & Entertainment Technology',
    keywords: [
      'game development studio',
      'mobile game development',
      'VR game development',
      'AR game development',
      'game engine development',
      'esports platform development',
      'gaming analytics platform',
      'game monetization solutions',
      'live streaming technology',
      'interactive entertainment',
      'game testing services',
      'gaming infrastructure',
      'multiplayer game development',
      'game art and animation',
      'gaming AI development',
      'game localization services',
      'gaming security solutions',
      'game publishing platform',
      'entertainment app development',
      'digital entertainment platform',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.unity.*',
      '*.unreal.*',
      '*.epic.*',
      '*.steam.*',
      '*.valve.*',
      '*.ea.*',
      '*.activision.*',
      '*.ubisoft.*',
      '*.nintendo.*',
      '*.sony.*',
      '*.microsoft.*',
      '*.roblox.*',
      '*.minecraft.*',
      '*.twitch.*',
      '*.youtube.*',
      '*.discord.*',
      '*.riot.*',
      '*.blizzard.*',
    ],
  },
  {
    id: 'logistics-supply-chain-tech',
    name: 'Logistics & Supply Chain Technology',
    keywords: [
      'supply chain management software',
      'logistics optimization platform',
      'warehouse management system',
      'transportation management system',
      'inventory optimization software',
      'freight management platform',
      'last mile delivery solutions',
      'supply chain analytics',
      'procurement software',
      'vendor management system',
      'demand forecasting software',
      'supply chain visibility',
      'logistics automation',
      'fleet management software',
      'route optimization software',
      'cold chain monitoring',
      'supply chain risk management',
      'logistics tracking platform',
      'distribution management system',
      'supply chain blockchain',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.sap.*',
      '*.oracle.*',
      '*.manhattan.*',
      '*.jda.*',
      '*.blue.*',
      '*.infor.*',
      '*.epicor.*',
      '*.kinaxis.*',
      '*.logility.*',
      '*.ups.*',
      '*.fedex.*',
      '*.dhl.*',
      '*.amazon.*',
      '*.flexport.*',
      '*.freightos.*',
      '*.project44.*',
      '*.fourkites.*',
      '*.transfix.*',
    ],
  },
  {
    id: 'cleantech-environmental',
    name: 'CleanTech & Environmental Technology',
    keywords: [
      'environmental technology solutions',
      'waste management technology',
      'water treatment technology',
      'air quality monitoring',
      'carbon capture technology',
      'environmental monitoring systems',
      'pollution control technology',
      'recycling technology solutions',
      'environmental compliance software',
      'green technology consulting',
      'environmental data analytics',
      'sustainability software',
      'environmental impact assessment',
      'clean energy technology',
      'environmental remediation',
      'eco-friendly technology',
      'environmental sensor technology',
      'climate monitoring systems',
      'environmental reporting software',
      'green building technology',
    ],
    isCustom: false,
    subCategoryId: 'it-services',
    domainBlacklist: [
      '*.veolia.*',
      '*.suez.*',
      '*.waste.*',
      '*.republic.*',
      '*.cleanenergy.*',
      '*.tesla.*',
      '*.ge.*',
      '*.siemens.*',
      '*.honeywell.*',
      '*.emerson.*',
      '*.schneider.*',
      '*.abb.*',
      '*.epa.*',
      '*.noaa.*',
      '*.nasa.*',
      '*.usgs.*',
      '*.energy.*',
      '*.doe.*',
    ],
  },
  {
    id: 'retail-brick-mortar-b2c',
    name: 'Retail Stores & Shopping Centers (B2C)',
    keywords: [
      'retail stores near me',
      'shopping centers in area',
      'clothing stores nearby',
      'electronics stores local',
      'furniture stores in town',
      'home goods stores',
      'sporting goods retailers',
      'bookstores near me',
      'toy stores local',
      'jewelry stores nearby',
      'shoe stores in area',
      'department stores local',
      'discount retailers',
      'specialty retail shops',
      'gift shops near me',
      'convenience stores local',
      'grocery stores nearby',
      'pharmacy retail locations',
      'beauty supply stores',
      'pet stores in area',
      'hardware stores local',
      'garden centers nearby',
      'auto parts stores',
      'thrift stores local',
      'antique shops near me',
      'craft stores in area',
      'music stores local',
      'video game stores',
      'outdoor gear retailers',
      'bike shops nearby',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.amazon.*',
      '*.walmart.*',
      '*.target.*',
      '*.bestbuy.*',
      '*.homedepot.*',
      '*.lowes.*',
      '*.macys.*',
      '*.kohls.*',
      '*.jcpenney.*',
      '*.sears.*',
      '*.costco.*',
      '*.samsclub.*',
      '*.cvs.*',
      '*.walgreens.*',
      '*.riteaid.*',
      '*.staples.*',
      '*.officedepot.*',
      '*.petco.*',
      '*.petsmart.*',
      '*.gamestop.*',
      '*.barnes.*',
      '*.toysrus.*',
      '*.dickssportinggoods.*',
      '*.rei.*',
      '*.cabelas.*',
    ],
  },
  {
    id: 'food-service-establishments-b2c',
    name: 'Food Service & Dining Establishments (B2C)',
    keywords: [
      'restaurants near me',
      'local dining establishments',
      'family restaurants nearby',
      'fast food locations',
      'pizza places in area',
      'coffee shops local',
      'bakeries near me',
      'ice cream shops',
      'sandwich shops nearby',
      'burger joints local',
      'ethnic restaurants',
      'fine dining establishments',
      'casual dining restaurants',
      'breakfast places near me',
      'lunch spots local',
      'dinner restaurants',
      'food trucks in area',
      'catering services local',
      'buffet restaurants',
      'steakhouses nearby',
      'seafood restaurants',
      'vegetarian restaurants',
      'bars and grills',
      'sports bars local',
      'wine bars near me',
      'breweries in area',
      'delis and markets',
      'donut shops local',
      'smoothie bars',
      'juice bars nearby',
    ],
    isCustom: false,
    subCategoryId: 'food-service-dining',
    domainBlacklist: [
      '*.mcdonalds.*',
      '*.subway.*',
      '*.starbucks.*',
      '*.kfc.*',
      '*.pizzahut.*',
      '*.dominos.*',
      '*.papajohns.*',
      '*.tacobell.*',
      '*.burgerking.*',
      '*.wendys.*',
      '*.chipotle.*',
      '*.panera.*',
      '*.dunkindonuts.*',
      '*.chilis.*',
      '*.applebees.*',
      '*.olivegarden.*',
      '*.redlobster.*',
      '*.outback.*',
      '*.dennys.*',
      '*.ihop.*',
      '*.crackerbarrel.*',
      '*.buffalowildwings.*',
      '*.hooters.*',
      '*.fridays.*',
      '*.cheesecakefactory.*',
    ],
  },
  {
    id: 'personal-services-b2c',
    name: 'Personal Services & Wellness Centers (B2C)',
    keywords: [
      'hair salons near me',
      'beauty salons local',
      'nail salons in area',
      'barbershops nearby',
      'spa services local',
      'massage therapy centers',
      'fitness gyms near me',
      'yoga studios local',
      'pilates studios',
      'tanning salons nearby',
      'tattoo parlors in area',
      'piercing studios',
      'dry cleaners local',
      'laundromats near me',
      'tailoring services',
      'shoe repair shops',
      'watch repair services',
      'jewelry repair local',
      'auto detailing services',
      'car wash locations',
      'pet grooming services',
      'veterinary clinics',
      'dental offices local',
      'optometry offices',
      'chiropractic clinics',
      'physical therapy centers',
      'urgent care clinics',
      'medical offices',
      'pharmacy locations',
      'daycare centers local',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.supercuts.*',
      '*.greatclips.*',
      '*.sportclips.*',
      '*.fantastic.*',
      '*.planetfitness.*',
      '*.anytimefitness.*',
      '*.curves.*',
      '*.orangetheory.*',
      '*.crossfit.*',
      '*.massage.*',
      '*.spafinder.*',
      '*.groupon.*',
      '*.yelp.*',
      '*.google.*',
      '*.facebook.*',
      '*.instagram.*',
      '*.nextdoor.*',
      '*.foursquare.*',
      '*.tripadvisor.*',
      '*.opentable.*',
      '*.booking.*',
      '*.expedia.*',
      '*.priceline.*',
      '*.hotels.*',
      '*.airbnb.*',
      '*.vrbo.*',
    ],
  },
  {
    id: 'professional-office-services-b2b',
    name: 'Professional Office Services (B2B)',
    keywords: [
      'accounting firms near me',
      'law offices local',
      'consulting firms in area',
      'marketing agencies nearby',
      'advertising agencies local',
      'real estate offices',
      'insurance agencies near me',
      'financial advisors local',
      'investment firms',
      'tax preparation services',
      'bookkeeping services',
      'payroll companies',
      'HR consulting firms',
      'business consultants',
      'management consulting',
      'IT consulting firms',
      'engineering firms local',
      'architectural offices',
      'design agencies nearby',
      'printing companies',
      'copy centers local',
      'office supply companies',
      'business equipment dealers',
      'commercial cleaning services',
      'security companies',
      'telecommunications providers',
      'internet service providers',
      'phone system companies',
      'office furniture dealers',
      'commercial real estate',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: [
      '*.deloitte.*',
      '*.pwc.*',
      '*.ey.*',
      '*.kpmg.*',
      '*.mckinsey.*',
      '*.bcg.*',
      '*.bain.*',
      '*.accenture.*',
      '*.ibm.*',
      '*.microsoft.*',
      '*.google.*',
      '*.amazon.*',
      '*.salesforce.*',
      '*.oracle.*',
      '*.sap.*',
      '*.adp.*',
      '*.paychex.*',
      '*.intuit.*',
      '*.quickbooks.*',
      '*.turbotax.*',
      '*.hrblock.*',
      '*.jacksonhewitt.*',
      '*.libertytax.*',
      '*.staples.*',
      '*.officedepot.*',
      '*.fedex.*',
    ],
  },
  {
    id: 'industrial-manufacturing-b2b',
    name: 'Industrial & Manufacturing Facilities (B2B)',
    keywords: [
      'manufacturing companies near me',
      'industrial facilities local',
      'factories in area',
      'production facilities',
      'assembly plants nearby',
      'machine shops local',
      'fabrication companies',
      'welding services industrial',
      'metal working shops',
      'plastic manufacturing',
      'chemical plants local',
      'food processing facilities',
      'packaging companies',
      'printing facilities',
      'textile manufacturers',
      'electronics manufacturing',
      'automotive suppliers',
      'aerospace manufacturers',
      'construction materials',
      'building supplies wholesale',
      'industrial equipment dealers',
      'machinery manufacturers',
      'tool and die shops',
      'precision machining',
      'injection molding companies',
      'sheet metal fabrication',
      'powder coating services',
      'heat treating facilities',
      'quality control labs',
      'industrial automation',
    ],
    isCustom: false,
    subCategoryId: 'commercial-trade-construction',
    domainBlacklist: [
      '*.ge.*',
      '*.boeing.*',
      '*.lockheed.*',
      '*.raytheon.*',
      '*.caterpillar.*',
      '*.johndeere.*',
      '*.ford.*',
      '*.gm.*',
      '*.chrysler.*',
      '*.toyota.*',
      '*.honda.*',
      '*.nissan.*',
      '*.bmw.*',
      '*.mercedes.*',
      '*.volkswagen.*',
      '*.siemens.*',
      '*.honeywell.*',
      '*.emerson.*',
      '*.schneider.*',
      '*.abb.*',
      '*.rockwell.*',
      '*.eaton.*',
      '*.parker.*',
      '*.dupont.*',
      '*.dow.*',
    ],
  },
  {
    id: 'commercial-trade-services-b2b',
    name: 'Commercial Trade & Construction Services (B2B)',
    keywords: [
      'commercial contractors near me',
      'general contractors local',
      'construction companies',
      'electrical contractors',
      'plumbing contractors commercial',
      'HVAC contractors business',
      'roofing contractors commercial',
      'flooring contractors',
      'painting contractors commercial',
      'drywall contractors',
      'concrete contractors',
      'excavation companies',
      'landscaping contractors commercial',
      'janitorial services commercial',
      'facility maintenance companies',
      'building maintenance services',
      'property management companies',
      'security system installers',
      'fire protection services',
      'elevator service companies',
      'glass and glazing contractors',
      'insulation contractors',
      'waterproofing contractors',
      'demolition companies',
      'site preparation contractors',
      'utility contractors',
      'telecommunications installers',
      'data cabling companies',
      'commercial moving services',
      'equipment rental companies',
    ],
    isCustom: false,
    subCategoryId: 'commercial-trade-construction',
    domainBlacklist: [
      '*.homedepot.*',
      '*.lowes.*',
      '*.menards.*',
      '*.builderssquare.*',
      '*.sherwin.*',
      '*.benjaminmoore.*',
      '*.behr.*',
      '*.valspar.*',
      '*.carrier.*',
      '*.trane.*',
      '*.lennox.*',
      '*.rheem.*',
      '*.goodman.*',
      '*.york.*',
      '*.kohler.*',
      '*.moen.*',
      '*.delta.*',
      '*.american.*',
      '*.toto.*',
      '*.grohe.*',
      '*.hansgrohe.*',
      '*.uhaul.*',
      '*.budget.*',
      '*.enterprise.*',
      '*.hertz.*',
      '*.avis.*',
      '*.ryder.*',
    ],
  },
  // New B2C Industries
  {
    id: 'fitness-wellness',
    name: 'Fitness & Wellness',
    keywords: [
      'fitness center near me',
      'gym membership',
      'personal trainer',
      'yoga studio',
      'pilates classes',
      'crossfit gym',
      'martial arts studio',
      'dance studio',
      'wellness center',
      'spa services',
      'massage therapy',
      'physical therapy clinic',
      'chiropractic office',
      'acupuncture clinic',
      'nutrition counseling',
      'weight loss center',
      'meditation center',
      'fitness bootcamp',
      'swimming pool fitness',
      'rock climbing gym',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.planetfitness.*',
      '*.anytimefitness.*',
      '*.24hourfitness.*',
      '*.lafitness.*',
      '*.goldsgym.*',
      '*.ymca.*',
    ],
  },
  {
    id: 'beauty-personal-care',
    name: 'Beauty & Personal Care',
    keywords: [
      'hair salon near me',
      'beauty salon',
      'nail salon',
      'barbershop',
      'spa services',
      'facial treatments',
      'eyebrow threading',
      'waxing salon',
      'massage therapy',
      'skincare clinic',
      'cosmetic services',
      'makeup artist',
      'permanent makeup',
      'laser hair removal',
      'botox clinic',
      'dermatology clinic',
      'tattoo parlor',
      'piercing studio',
      'tanning salon',
      'beauty supply store',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.sephora.*',
      '*.ulta.*',
      '*.sallybeauty.*',
      '*.supercuts.*',
      '*.greatclips.*',
      '*.sportclips.*',
    ],
  },
  {
    id: 'home-improvement-repair',
    name: 'Home Improvement & Repair',
    keywords: [
      'handyman services',
      'home repair near me',
      'plumber near me',
      'electrician services',
      'HVAC repair',
      'roofing contractor',
      'painting services',
      'flooring installation',
      'kitchen remodeling',
      'bathroom renovation',
      'landscaping services',
      'tree service',
      'lawn care',
      'pest control',
      'cleaning services',
      'carpet cleaning',
      'window cleaning',
      'gutter cleaning',
      'pressure washing',
      'appliance repair',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.homedepot.*',
      '*.lowes.*',
      '*.menards.*',
      '*.angieslist.*',
      '*.homeadvisor.*',
      '*.thumbtack.*',
    ],
  },
  {
    id: 'travel-tourism',
    name: 'Travel & Tourism',
    keywords: [
      'travel agency near me',
      'vacation planning',
      'cruise booking',
      'hotel reservations',
      'flight booking',
      'tour operator',
      'travel consultant',
      'honeymoon planning',
      'group travel',
      'corporate travel',
      'adventure tours',
      'guided tours',
      'travel insurance',
      'visa services',
      'passport services',
      'car rental',
      'vacation rentals',
      'bed and breakfast',
      'resort booking',
      'destination wedding planning',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.expedia.*',
      '*.booking.*',
      '*.priceline.*',
      '*.kayak.*',
      '*.orbitz.*',
      '*.travelocity.*',
    ],
  },
  {
    id: 'childcare-early-education',
    name: 'Childcare & Early Education',
    keywords: [
      'daycare near me',
      'preschool',
      'childcare center',
      'nursery school',
      'kindergarten',
      'after school program',
      'summer camp',
      'babysitting services',
      'nanny services',
      'tutoring services',
      'music lessons',
      'art classes for kids',
      'swimming lessons',
      'dance classes kids',
      'martial arts kids',
      'sports programs kids',
      'educational toys',
      'learning center',
      'montessori school',
      'waldorf school',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.kindercare.*',
      '*.brightbeginnings.*',
      '*.childtime.*',
      '*.lapetiteacademy.*',
      '*.primroseschools.*',
      '*.goddardschool.*',
    ],
  },
  {
    id: 'pet-services-enhanced',
    name: 'Pet Services & Veterinary Care',
    keywords: [
      'veterinarian near me',
      'animal hospital',
      'pet grooming',
      'dog grooming',
      'cat grooming',
      'pet boarding',
      'dog daycare',
      'pet sitting',
      'dog walking',
      'pet training',
      'dog training',
      'pet store',
      'pet supplies',
      'animal clinic',
      'emergency vet',
      'pet insurance',
      'pet photography',
      'pet cremation',
      'dog park',
      'pet adoption center',
    ],
    isCustom: false,
    subCategoryId: 'retail-consumer-services',
    domainBlacklist: [
      '*.petco.*',
      '*.petsmart.*',
      '*.chewy.*',
      '*.petfinder.*',
      '*.rover.*',
      '*.wag.*',
    ],
  },
  // New B2B Industries
  {
    id: 'manufacturing-supply-chain',
    name: 'Manufacturing Supply Chain',
    keywords: [
      'manufacturing suppliers',
      'industrial suppliers',
      'raw materials supplier',
      'component manufacturing',
      'parts supplier',
      'industrial equipment',
      'machinery supplier',
      'tool and die',
      'metal fabrication',
      'plastic manufacturing',
      'chemical supplier',
      'packaging supplier',
      'logistics provider',
      'freight forwarder',
      'warehouse services',
      'distribution center',
      'supply chain management',
      'procurement services',
      'vendor management',
      'quality control services',
    ],
    isCustom: false,
    subCategoryId: 'commercial-trade-construction',
    domainBlacklist: [
      '*.alibaba.*',
      '*.thomasnet.*',
      '*.globalspec.*',
      '*.grainger.*',
      '*.mcmaster.*',
      '*.fastenal.*',
    ],
  },
  {
    id: 'business-consulting',
    name: 'Business Consulting',
    keywords: [
      'business consultant',
      'management consulting',
      'strategy consulting',
      'operations consulting',
      'process improvement',
      'business analysis',
      'organizational development',
      'change management',
      'project management',
      'business planning',
      'market research',
      'competitive analysis',
      'business intelligence',
      'performance optimization',
      'efficiency consulting',
      'lean consulting',
      'six sigma consulting',
      'digital transformation',
      'technology consulting',
      'IT consulting',
    ],
    isCustom: false,
    subCategoryId: 'professional-services',
    domainBlacklist: ['*.mckinsey.*', '*.bcg.*', '*.bain.*', '*.deloitte.*', '*.pwc.*', '*.ey.*'],
  },
]

/**
 * Contact page keywords for scraping
 */
export const CONTACT_KEYWORDS = [
  'contact',
  'about us',
  'corporate',
  'investor',
  'team',
  'staff',
  'directory',
  'location',
  'office',
]
