# Docker Security Scanning Configuration
# Container security scanning with Trivy and Docker Scout

name: Docker Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  docker-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for scanning
        run: |
          docker build -f Dockerfile.production -t business-scraper:security-scan .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "business-scraper:security-scan"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          severity: "CRITICAL,HIGH"

      - name: Docker Scout CVE scan
        uses: docker/scout-action@v1
        if: github.event_name != 'pull_request'
        with:
          command: cves
          image: business-scraper:security-scan
          sarif-file: scout-results.sarif

      - name: Upload Scout scan results
        uses: github/codeql-action/upload-sarif@v3
        if: github.event_name != 'pull_request' && always()
        with:
          sarif_file: "scout-results.sarif"

      - name: Generate security report
        run: |
          echo "# Docker Security Scan Report" > security-report.md
          echo "## Scan Date: $(date)" >> security-report.md
          echo "## Image: business-scraper:security-scan" >> security-report.md
          echo "" >> security-report.md

          # Add Trivy results summary
          echo "### Trivy Vulnerability Scan" >> security-report.md
          trivy image --format table business-scraper:security-scan >> security-report.md

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: security-report.md
          retention-days: 30
