# Self-Documenting Enhancement Workflow with Coverage & Alerts
# Implements an enhancement, creates a GitHub Issue, detects affected files,
# runs file-specific or documentation tests (linting, spelling, link validation, grammar/style checks),
# calculates pass/fail coverage, updates the Issue with results,
# alerts if success < 98.99%, and closes the Issue only if coverage target is met.

name: Self-Documenting Enhancement with Coverage

on:
  workflow_dispatch:
    inputs:
      enhancement:
        description: 'Description of the enhancement or documentation update'
        required: true
        type: string
      files:
        description: 'Comma-separated list of target files for edit/refactor/re-evaluation'
        required: false
        default: 'README.md,docs/UX-ToDo.html,docs/Remaining-Work.html,docs/MVP2.html,docs/MVP.html,docs/MVP_REFACTOR_SUMMARY.html,docs/CONFIGURATION.html,docs/ai-features.html,docs/CodeReviewActions.html,docs/stripe-ai-prompts.html'
        type: string
      assignees:
        description: 'Comma-separated list of GitHub usernames to assign the Issue to'
        required: false
        default: 'mytech-today-now'
        type: string
      labels:
        description: 'Comma-separated list of GitHub labels to apply'
        required: false
        default: 'bug,enhancement,critical,needs review'
        type: string
      pull_request_url:
        description: 'URL of the pull request implementing the enhancement (optional, for auto-linking)'
        required: false
        type: string
      alert_mentions:
        description: 'Comma-separated GitHub usernames to mention in alerts if coverage < 98.99%'
        required: false
        default: 'mytech-today-now'
        type: string

env:
  NODE_VERSION: "18"
  COVERAGE_THRESHOLD: "98.99"

jobs:
  self-documenting-enhancement:
    name: Self-Documenting Enhancement with Coverage Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci --force
          # Install additional testing tools
          npm install -g markdownlint-cli markdown-link-check codespell write-good htmlhint vale || true

      - name: Plan Enhancement
        id: plan
        run: |
          echo "🎯 Planning enhancement: ${{ github.event.inputs.enhancement }}"
          mkdir -p enhancement-results
          echo "${{ github.event.inputs.enhancement }}" > enhancement-results/description.txt
          
          # Parse file list
          IFS=',' read -ra FILE_ARRAY <<< "${{ github.event.inputs.files }}"
          printf '%s\n' "${FILE_ARRAY[@]}" > enhancement-results/target-files.txt
          
          echo "Target files:"
          cat enhancement-results/target-files.txt

      - name: Implement Enhancement
        id: implement
        run: |
          echo "🔧 Implementing enhancement across affected areas..."
          echo "Enhancement implementation would happen here in a real scenario"
          echo "For this workflow, we'll proceed to testing the specified files"

      - name: Create GitHub Issue
        id: create_issue
        uses: actions/github-script@v7
        with:
          script: |
            const assignees = '${{ github.event.inputs.assignees }}'.split(',').map(a => a.trim()).filter(a => a);
            const labels = '${{ github.event.inputs.labels }}'.split(',').map(l => l.trim()).filter(l => l);
            const files = '${{ github.event.inputs.files }}'.split(',').map(f => f.trim()).filter(f => f);
            
            const issueBody = `## Enhancement Summary
            ${{ github.event.inputs.enhancement }}
            
            ## Expected Outcome
            - Seamless functionality
            - Errors handled
            - UX uninterrupted
            
            ## Testing Notes
            - Tests run per affected file
            - Target success ≥ ${{ env.COVERAGE_THRESHOLD }}%
            
            ## Additional Context
            - Pull Request: ${{ github.event.inputs.pull_request_url || 'Not provided' }}
            
            ## Affected Files:
            ${files.map(f => `- ${f}`).join('\n')}
            
            ---
            *This issue was created by the Self-Documenting Enhancement Workflow*
            `;
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Enhancement] ${{ github.event.inputs.enhancement }}`,
              body: issueBody,
              assignees: assignees,
              labels: labels
            });
            
            console.log(`Created issue #${issue.data.number}`);
            return issue.data.number;

      - name: Run Tests & Calculate Coverage
        id: run_tests
        run: |
          echo "🧪 Running comprehensive tests and calculating coverage..."
          
          ISSUE_NUMBER="${{ steps.create_issue.outputs.result }}"
          PASS_COUNT=0
          FAIL_COUNT=0
          TEST_RESULTS=""
          
          mkdir -p test-results/coverage-analysis
          
          # Read target files
          while IFS= read -r FILE; do
            echo "Testing file: $FILE"
            
            # Determine test command based on file type
            if [[ $FILE == *.js ]]; then
              CMD="npm test -- $FILE"
            elif [[ $FILE == *.py ]]; then
              CMD="pytest $FILE"
            elif [[ $FILE == *.md ]]; then
              CMD="markdownlint $FILE && markdown-link-check $FILE && codespell $FILE"
            elif [[ $FILE == *.html ]]; then
              CMD="htmlhint $FILE && codespell $FILE"
            else
              CMD="codespell $FILE"
            fi
            
            echo "Running: $CMD"
            
            # Run test and capture result
            if eval "$CMD" > "test-results/coverage-analysis/$(basename "$FILE").log" 2>&1; then
              RESULT="PASS"
              STATUS="✅"
              PASS_COUNT=$((PASS_COUNT + 1))
            else
              RESULT="FAIL"
              STATUS="❌"
              FAIL_COUNT=$((FAIL_COUNT + 1))
            fi
            
            OUTPUT=$(head -5 "test-results/coverage-analysis/$(basename "$FILE").log" | tr '\n' ' ')
            
            TEST_RESULTS+="\n### $STATUS $FILE\n**Command:** \`$CMD\`\n**Result:** $RESULT\n**Output Preview:**\n\`\`\`\n$OUTPUT\n\`\`\`\n\n"
            
          done < enhancement-results/target-files.txt
          
          # Calculate success percentage
          TOTAL=$((PASS_COUNT + FAIL_COUNT))
          if [ $TOTAL -eq 0 ]; then
            SUCCESS_PERCENT=100
          else
            SUCCESS_PERCENT=$(echo "scale=2; $PASS_COUNT * 100 / $TOTAL" | bc)
          fi
          
          SUMMARY="**Test Summary:** $PASS_COUNT passed, $FAIL_COUNT failed, success rate: ${SUCCESS_PERCENT}%"
          
          echo "pass_count=$PASS_COUNT" >> $GITHUB_OUTPUT
          echo "fail_count=$FAIL_COUNT" >> $GITHUB_OUTPUT
          echo "success_percent=$SUCCESS_PERCENT" >> $GITHUB_OUTPUT
          echo "total_tests=$TOTAL" >> $GITHUB_OUTPUT
          
          # Store results for issue update
          echo "$TEST_RESULTS" > test-results/test-summary.md
          echo "$SUMMARY" >> test-results/test-summary.md
          
          echo "Coverage calculation completed: ${SUCCESS_PERCENT}%"

      - name: Update GitHub Issue with Results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const issueNumber = ${{ steps.create_issue.outputs.result }};
            const successPercent = parseFloat('${{ steps.run_tests.outputs.success_percent }}');
            const threshold = parseFloat('${{ env.COVERAGE_THRESHOLD }}');
            
            // Read test results
            let testResults = '';
            try {
              testResults = fs.readFileSync('test-results/test-summary.md', 'utf8');
            } catch (error) {
              testResults = 'Test results not available';
            }
            
            let alertMsg = '';
            if (successPercent < threshold) {
              const mentions = '${{ github.event.inputs.alert_mentions }}'.split(',').map(u => `@${u.trim()}`).join(' ');
              alertMsg = `\n\n⚠️ **ALERT: Coverage below target (${threshold}%)!** ${mentions} please review.\n`;
            }
            
            const updateBody = `## 🔄 Actual Test Results
            
            ${testResults}
            
            ### Coverage Analysis
            - **Pass Count:** ${{ steps.run_tests.outputs.pass_count }}
            - **Fail Count:** ${{ steps.run_tests.outputs.fail_count }}
            - **Success Rate:** ${{ steps.run_tests.outputs.success_percent }}%
            - **Threshold:** ${{ env.COVERAGE_THRESHOLD }}%
            - **Status:** ${successPercent >= threshold ? '✅ MEETS THRESHOLD' : '❌ BELOW THRESHOLD'}
            
            ${alertMsg}
            
            ---
            *Results updated automatically by Self-Documenting Enhancement Workflow*
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: updateBody
            });

      - name: Conditional Close GitHub Issue
        if: steps.run_tests.outputs.success_percent >= env.COVERAGE_THRESHOLD
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.create_issue.outputs.result }};
            
            const closingComment = `## ✅ Enhancement Implementation Completed
            
            ### Closing Notes
            - ✅ Enhancement implemented successfully
            - ✅ All affected areas verified
            - ✅ Tests executed per file
            - ✅ Coverage threshold met: ${{ steps.run_tests.outputs.success_percent }}% ≥ ${{ env.COVERAGE_THRESHOLD }}%
            - ✅ Linked pull request: ${{ github.event.inputs.pull_request_url || 'Not provided' }}
            
            **Enhancement completed successfully! 🎉**
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: closingComment
            });
            
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed'
            });

      - name: Alert on Low Coverage
        if: steps.run_tests.outputs.success_percent < env.COVERAGE_THRESHOLD
        run: |
          echo "❌ Coverage below threshold. Issue NOT closed due to coverage below threshold."
          echo "Team alerted via GitHub issue comments."
          exit 1

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: self-documenting-enhancement-results
          path: |
            enhancement-results/
            test-results/
          retention-days: 30

      - name: Workflow Summary
        if: always()
        run: |
          echo "## 🎯 Self-Documenting Enhancement Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Enhancement:** ${{ github.event.inputs.enhancement }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Files Tested:** ${{ steps.run_tests.outputs.total_tests }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Pass Count:** ${{ steps.run_tests.outputs.pass_count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Fail Count:** ${{ steps.run_tests.outputs.fail_count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Success Rate:** ${{ steps.run_tests.outputs.success_percent }}%" >> $GITHUB_STEP_SUMMARY
          echo "- **Threshold:** ${{ env.COVERAGE_THRESHOLD }}%" >> $GITHUB_STEP_SUMMARY
          echo "- **Issue Created:** #${{ steps.create_issue.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Issue Status:** ${{ steps.run_tests.outputs.success_percent >= env.COVERAGE_THRESHOLD && 'Closed' || 'Open (Low Coverage)' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflow Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
